from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from database import get_db
from models.user import User
from schemas.auth import SignUpRequest, SignInRequest, TokenResponse, UserResponse
from utils.security import hash_password, verify_password
from utils.auth import create_access_token

router = APIRouter(prefix="/api/auth", tags=["Authentication"])

@router.post("/signup", response_model=TokenResponse, status_code=status.HTTP_201_CREATED)
async def signup(request: SignUpRequest, db: Session = Depends(get_db)):
    """
    Register a new user
    """
    # 1. Check for duplicate email
    existing_user = db.query(User).filter(User.email == request.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered"
        )
    
    # 2. Check for duplicate username (generated by frontend)
    existing_username = db.query(User).filter(User.username == request.username).first()
    if existing_username:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username collision. Please try again."
        )
    
    # 3. Logic: Split fullName into first_name and last_name for the DB
    # If your DB has a 'fullName' column instead, change this line!
    # Here we assume DB has first_name/last_name columns.
    names = request.fullName.strip().split(" ", 1)
    first_name = names[0]
    last_name = names[1] if len(names) > 1 else ""

    hashed_pwd = hash_password(request.password)
    
    new_user = User(
        email=request.email,
        username=request.username,
        hashed_password=hashed_pwd,
        first_name=first_name,  # Saved from split
        last_name=last_name,    # Saved from split
        company=request.company,
        industry=request.industry
    )
    
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    
    access_token = create_access_token(data={"sub": str(new_user.id), "email": new_user.email})
    
    # We need to reconstruct the response object to match UserResponse schema
    # The UserResponse expects 'fullName', but our DB object has first/last.
    # So we can manually create the response or rely on model_validate if UserResponse is smart enough (it usually isn't with computed fields).
    # Easier hack: Just patch the object before validation or return a dict.
    
    return TokenResponse(
        access_token=access_token,
        user=UserResponse(
            id=new_user.id,
            email=new_user.email,
            username=new_user.username,
            fullName=f"{new_user.first_name} {new_user.last_name}".strip(),
            company=new_user.company,
            industry=new_user.industry,
            created_at=new_user.created_at
        )
    )

@router.post("/signin", response_model=TokenResponse)
async def signin(request: SignInRequest, db: Session = Depends(get_db)):
    """
    Authenticate an existing user
    """
    user = db.query(User).filter(User.email == request.email).first()
    
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials"
        )

    if not verify_password(request.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials"
        )
    
    access_token = create_access_token(data={"sub": str(user.id), "email": user.email})
    
    return TokenResponse(
        access_token=access_token,
        user=UserResponse(
            id=user.id,
            email=user.email,
            username=user.username,
            fullName=f"{user.first_name} {user.last_name}".strip(),
            company=user.company,
            industry=user.industry,
            created_at=user.created_at
        )
    )
